### ISSUE TITLE
Check if back-end is still fully functional

### ISSUE THREAD

**Issue by AtilioA** [AtilioA/AlertaDoTesouro#22]
That's right. NO AUTOMATED TESTING IS ALLOWED IN THE VICINITY OF THIS REPOSITORY.

User creation might not be working properly, emailing can be reverted back to mailtrap. I bet notifications are borked too.

**Comment by Henriquelay** [comment]
Honestly automating is probably _still_ faster than checking this mess manually + notified when breaks again.

**Comment by AtilioA** [comment]
Closing in favor of #27.
