### ISSUE TITLE
Create automated tests

### ISSUE THREAD

**Issue by AtilioA** [AtilioA/AlertaDoTesouro#27]
we need some QA smh jp is asking for it

**Comment by Henriquelay** [comment]
It makes a lot of sense to wait for #46 merge to branch this off. Will rebase 27-create-automated-tests when it does.

**Comment by Henriquelay** [comment]
Do you prefer `.spec.ts` or `.test.ts`? Asking for a friend

**Comment by Henriquelay** [comment]
I am tending towards `.test` simply because it's not a specification -- we haven't done TDD at all.

**Comment by AtilioA** [comment]
Same

**Comment by Henriquelay** [comment]
Socar mais testes :disappointed:

**Comment by AtilioA** [comment]
LATER

**Comment by Henriquelay** [comment]
Vamo merjar isso aqui e fazer outra pra adicionar mais depois só pra gente ter o CI de covas
