### ISSUE TITLE
Create ToS and Privacy Statement

### ISSUE THREAD

**Issue by AtilioA** [AtilioA/AlertaDoTesouro#36]
Since this web app heavily relies on creating an account to enable usage, it is reasonable to provide a Terms of Service and a Privacy Statement for all potential users to read.

**Comment by AtilioA** [comment]
tb pensei mas n é bem documentação n

**Comment by Henriquelay** [comment]
~Hmmm talvez uma nova tag?
Legal ou algo assim?
Human Resources~

Na verdade acho que não surgirá issues o bastante pra justificar mais uma categoria

**Comment by AtilioA** [comment]
Exato

**Comment by AtilioA** [comment]
tfw github team needs to open an issue about issues on github (not automatically closing as of github issues update)

**Comment by Henriquelay** [comment]
Was gonna comment about that just now.
