### ISSUE TITLE
New feature: Resend confirmation email

### ISSUE THREAD

**Issue by Henriquelay** [AtilioA/AlertaDoTesouro#48]
Consider the following situation:  
1. User creates an account
2. Server sends email promtping user to confirm email address
3. Email is sent to user, but is {not delivered, rejected, bounced, fell into a deletion rule, etc}

Then:  
* User can't login because account is not confirmed
* User can't create a new account on the same email address

**Comment by AtilioA** [comment]
Just send it again when attempting to create a new account with the same e-mail, if the account is not confirmed.

**Comment by Henriquelay** [comment]
> Just send it again when attempting to create a new account with the same e-mail, if the account is not confirmed.

When? When you try to register a registered but not confirmed email? Then it would be nice to also update fhe password since previous registration might have been long ago. Or fvck it there's #41 around.
