### ISSUE TITLE
Implement functionality for `/dashboard` front-end route

### ISSUE THREAD

**Issue by AtilioA** [AtilioA/AlertaDoTesouro#49]
Market status info can be retrieved from the API: `["response"]["TrsrBondMkt"]` yields:

1. `opngDtTm`: opening datetime
2. `clsgDtTm`: closing datetime
3. `qtnDtTm`: ? (for the love of God stop aggressively abbreviating things!!). anyways, this should be of no use to us
4. `sts`: market status ("Aberto" or "Fechado")

We can format those as:
'Mercado aberto/Mercado fechado: [current time in HHhMM]'
'Horário de funcionamento: de HHhMM às HHhMM.'

Back when I draw this view, I was thinking about having the 'Atualizado às XX/XX/XXXX, XX:XX.' with a refresh button to its left, allowing the user to refresh the data without reloading the whole page. This might be a bit unnecessary since treasury bonds rates don't fluctuate too heavily within a day.
This simplified version cleans up some information and space, concentrating information tightly (without going overboard as well).

The cards are missing all of their functionality as well. This is where the users can subscribe to/create notifications.

_Extra_: The grey circled 'i' would flip the card and exhibit information about the bond, but that would be even harder. However, it is a reasonable solution since the text is rather long. I'm still not sure what to make of it. To start off, we might leave it as a simple tooltip text.

_Extra_: it would _still_ be nice if the dashboard automatically updated the rates every 15 minutes. muh SPA

**Comment by Henriquelay** [comment]
Can we work on a mock together first? Or is there an existing Figma link or something?

**Comment by AtilioA** [comment]
I thought I had sent you this: https://www.figma.com/file/m4KROrOpFC3iEjaI6aCLMQ/Dashboard?node-id=0%3A1
~~(I don't know if I got the permissions right :nerd_face:)~~ I'm sharing the prototype for this page and allowing anyone with the link to view
