### ISSUE TITLE
Repeated files

### ISSUE THREAD

**Issue by Henriquelay** [AtilioA/AlertaDoTesouro#59]
What is the difference between [ResetUserPasswordService](https://github.com/AtilioA/AlertaDoTesouro/blob/develop/server/src/services/ResetUserPasswordService.ts) and [UpdateUserService](https://github.com/AtilioA/AlertaDoTesouro/blob/develop/server/src/services/UpdateUserService.ts)? Those files seems very much identical

**Comment by AtilioA** [comment]
`ResetUserPasswordService` does not require the old password, unlike `UpdateUserService`. It also handles fewer of the user's attributes.

**Comment by Henriquelay** [comment]
Do you think it's sensible to treat in a single one for both operations, since both are UPDATING a field?

We check if newPassword is found and if it is, we treat as a password change aswell. Otherwise, regular attributes updating.
Can we bring field checking to the controller? Is it a good practice?

**Comment by AtilioA** [comment]
> Can we bring field checking to the controller? Is it a good practice?

I think it's up to the service to handle that.

In any case, we shouldn't be worrying about this :(

**Comment by Henriquelay** [comment]
Whatsapp
Can we transform this into a MVC best practices discussion then?
I do believe it's more about
Controller - Connection, input validation, technical means to accomplish thing
Service - do the thing, devoid of other types of validation, pure business logic.

**Comment by AtilioA** [comment]
We aren't using an MVC architecture but sure
This discussion is similar to ours and the answers are especially relevant: https://stackoverflow.com/questions/46479889/validation-in-controller-or-service

**Comment by AtilioA** [comment]
😈
