### ISSUE TITLE
Use docker compose to run locally

### ISSUE THREAD

**Issue by Henriquelay** [AtilioA/AlertaDoTesouro#8]
Instead of only running backend in containers, a [docker-compose](https://docs.docker.com/compose/) should be more accessible and easier to the end-user, since they will need docker to run the backend anyway. That should even help when developing frontend.

What needs to be done in order to achieve it:  
* Create a dockerfile that builds the project and then runs it.
* Create a docker-compose file that runs both the backend and then the frontend, all in the same network. In the future, the backend application can be in more than one network, to be in a separate network with only backend app and frontend. 

With this, you should be able to run all applications (in the proper order) with `docker-compose up`, creating a docker container for each service instead of doing that with separate commands and the application in the shell session.

**Comment by AtilioA** [comment]
n acredito que closamo essa hein :raised_hands:

**Comment by AtilioA** [comment]
Reopening as we still need a service for the web app, and I'd prefer to reopen the same issue instead of creating a new one.

**Comment by AtilioA** [comment]
n acredito que closamo essa hein raised_hands
